
service: pwa-jwt
app: pwa-jwt
org: chauchausoup

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
      - http:
          path: /login
          method: post
      - http:
          path: /register
          method: post
    
