
service: pwa-jwt
app: pwa-jwt
org: chauchausoup
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /login
          method: post
      - httpApi:
          path: /register
          method: post
    
