AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Sample SAM Template for sam-app.

Globals:
  Function:
    Timeout: 30

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: handler.hello
      Runtime: nodejs12.x
      Events:
        Home:
          Type: Api
          Properties:
            Path: /
            Method: get
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
        Register:
          Type: Api
          Properties:
            Path: /register
            Method: post
